[package]
authors = ["Benjamin Matuszewski <benjamin.matuszewski@ircam.fr>"]
edition = "2021"
name = "node-web-audio-api"
version = "0.21.5"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
audio_thread_priority = "0.32.0"
crossbeam-channel = "0.5.12"
napi = { version="2.16", features=["napi9", "tokio_rt"] }
napi-derive = { version="2.16" }
thread-priority = "1.1.0"
web-audio-api = "=1.1"
# web-audio-api = { path = "../web-audio-api-rs" }

[target.'cfg(all(any(windows, unix), target_arch = "x86_64", not(target_env = "musl")))'.dependencies]
mimalloc = {version = "0.1"}

[build-dependencies]
napi-build = "1"

[profile.release]
lto = true

[features]
jack = ["web-audio-api/cpal-jack"]
