[package]
authors = ["Benjamin Matuszewski <benjamin.matuszewski@ircam.fr>"]
edition = "2021"
name = "node-web-audio-api"
version = "0.18.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = {version="2.15", features=["napi9", "tokio_rt"]}
napi-derive = "2.15"
uuid = {version="1.6.1", features = ["v4", "fast-rng"]}
# web-audio-api = "1.0.0-rc.5"
web-audio-api = { path = "../web-audio-api-rs" }

[target.'cfg(all(any(windows, unix), target_arch = "x86_64", not(target_env = "musl")))'.dependencies]
mimalloc = {version = "0.1"}

[build-dependencies]
napi-build = "1"

[profile.release]
lto = true

[features]
jack = ["web-audio-api/cpal-jack"]
